show_project/show_project/show_app/urls.py
from django.urls import path
from . import views
app_name = 'show_app'

urlpatterns = [
    path('',views.index,name='index'),
    path('show/<int:show_id>/',views.detail,name='detail'),
    path('add/',views.add_show,name='add_show'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),



]

show_project/show_project/show_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("show_app.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

show_project/show_project/show_app/models.py
from django.db import models

# Create your models here.

class Show(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

show_project/show_project/show_app/forms.py
from django import forms
from  . models import Show

class ShowForm(forms.ModelForm):
    class Meta:
        model = Show
        fields = ['name','desc','year','img']

show_project/show_project/show_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Show
from .forms import ShowForm
# Create your views here.
def index(request):
    show = Show.objects.all()
    context = {
        'show_list':show
    }
    return  render(request,'index.html',context)


def detail(request,show_id):
    show = Show.objects.get(id=show_id)
    return render(request,"detail.html",{'show':show})

def add_show(request):
    if request.method == "POST":
        name = request.POST.get('name', )
        desc = request.POST.get('desc', )
        year = request.POST.get('year', )
        img = request.FILES['img']
        show = Show(name=name, desc=desc, year=year, img=img)
        show.save()
        return redirect('/')
    return render(request,'add.html')

def update(request,id):
    show = Show.objects.get(id=id)
    form = ShowForm(request.POST or None,request.FILES,instance=show)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'show':show})

def delete(request,id):
    if request.method == 'POST':
        show = Show.objects.get(id=id)
        show.delete()
        return redirect('/')
    return render(request,'delete.html')

show_project/show_project/templates/add.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% block content %}
    <input type="text" name="name" placeholder="Enter your show name"><br>
    <input type="text" name="desc" placeholder="Enter the show description"><br>
    <input type="text" name="year" placeholder="Enter your show year"><br>
    <input type="file" name="img"><br>
    <input type="submit">
</form>
{% endblock %}

show_project/show_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="#">
        <br>
      <center style="top:20%; left:40%; position:absolute; transform:transform;">Online Film Store</center></a>
    </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

show_project/show_project/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are you want to delete this film?
    <input type="submit">
</form>

show_project/show_project/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6"><br>
<img src="{{ show.img.url }}" width="200" height="200">
              </div>
        <div class="col-md-4"><br>
     <h6>{{ show.name }}</h6>
     <h6> {{ show.desc }}</h6>
     <h6> {{ show.year}}</h6>
<a class="btn btn-warning" href="{% url 'show_app:update' show.id %}">Update</a>
<a class="btn btn-danger" href="{% url 'show_app:delete' show.id %}">Delete</a>
            </div>
         </div>
</div>
{% endblock %}

show_project/show_project/templates/edit.html
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>

show_project/show_project/templates/index.html
{% extends 'base.html' %}
{% block body %}
<body style="background-color: aqua">
<div class="container">
    <div class="row">
{% for i in show_list %}
        <div class="col-sm-3"><br>
            <div class="card" style="width:16rem;">
<img src="{{ i.img.url }}" width="254px" height="300px">
              <div class="card-body">
                   <h5 class="card-title">{{i.name}}</h5>
                  <p class="card-text">{{i.desc}}</p>
<a href="{% url 'show_app:detail' i.id %}" class="btn btn-primary">Go somewhere</a>
              </div>
            </div>
        </div>
    {% endfor %}
    </div>
</div>
    <center  style="left:90%; position:absolute; transform:transform;"><br>
  <a href="add" class="card-link"><button class=" btn btn-success">Add New</button></a>
</center>
<br>
{% endblock %}
</body>